# Generated by Django 3.0.1 on 2020-01-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=10)),
                ('maxLevel', models.IntegerField(default=10)),
                ('heroes', models.BooleanField()),
                ('xp', models.IntegerField(default=40)),
                ('card_images', models.ImageField(upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DeckUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Cards')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.DeckUser')),
            ],
        ),
    ]
