# Generated by Django 3.0.1 on 2020-01-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='type',
            field=models.CharField(default='troops', max_length=30),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_images',
            field=models.ImageField(null=True, upload_to='card_images/'),
        ),
    ]
