# Generated by Django 3.0.1 on 2020-01-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trading', '0002_auto_20200101_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=None)),
                ('card_received', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_received', to='trading.Cards')),
                ('card_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sent', to='trading.Cards')),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='accounts.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='accounts.Profile')),
            ],
        ),
    ]
