# Generated by Django 3.0.1 on 2020-01-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
