# Generated by Django 3.0.1 on 2020-01-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trading', '0004_auto_20200103_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='card_received',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='card_received', to='trading.Cards'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='receiver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='accounts.Profile'),
        ),
    ]
