# Generated by Django 3.0.1 on 2020-01-02 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='threads',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
