# Generated by Django 3.0.1 on 2019-12-31 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pictures/')),
                ('personnage', models.IntegerField(choices=[(50, 'Barbarian King'), (40, 'Archer Queen'), (30, 'Battle Machine'), (20, 'P.E.K.K.A'), (10, 'Healer')], default=10)),
                ('points', models.IntegerField(default=10)),
                ('coins', models.IntegerField(default=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
